module:
  automated_cron: 0
  backup_migrate: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_update: 0
  config_update_ui: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_generic: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  language: 0
  layout_discovery: 0
  link: 0
  menu_ui: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  path: 0
  shortcut: 0
  styleguide: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  ultimate_cron: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  visiolms_course: 0
  visiolms_lesson: 0
  visiolms_unit: 0
  menu_link_content: 1
  views: 10
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  semantic: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
